#!/usr/bin/env python3
"""Writes Canto/Resources/Localizable.xcstrings and InfoPlist.xcstrings (English source, Russian, Hebrew)."""
import json, os

from strings_he import HE, INFO_PLIST_HE

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

RU = {
    "Starting the microphone…": "Подключаю микрофон…",
    "Unload the model after": "Выгружать модель через",
    "Never": "Никогда",
    "1 minute": "1 минуту",
    "5 minutes": "5 минут",
    "15 minutes": "15 минут",
    "Frees memory while you are not dictating. The model loads again when you press the shortcut, usually while you are still speaking.": "Освобождает память, пока вы не диктуете. Модель загружается снова при нажатии сочетания клавиш, обычно ещё пока вы говорите.",
    "AI skills": "ИИ-скиллы",
    "Skills": "Скиллы",
    "Turn off all skills": "Выключить все скиллы",
    "Runs on": "Где работает",
    "Local server": "Локальный сервер",
    "Server": "Сервер",
    "Reload skills": "Обновить скиллы",
    "Ollama: http://localhost:11434/v1, LM Studio: http://localhost:1234/v1. The text stays on your Mac.": "Ollama: http://localhost:11434/v1, LM Studio: http://localhost:1234/v1. Текст не покидает ваш Mac.",
    "A skill is a Markdown file with instructions for the AI: clean up, organize, fix technical terms, translate. Skills that are on run together in one request after the cleanup and add about a second; the number shows their order.": "Скилл — это Markdown-файл с инструкцией для ИИ: почистить текст, разложить по разделам, поправить технические термины, перевести. Включённые скиллы работают вместе, одним запросом после очистки, и добавляют около секунды; цифра показывает их порядок.",
    "Needed for skills on OpenAI and for recognition with OpenAI. Local recognition works without it.": "Нужен для скиллов и распознавания через OpenAI. Локальное распознавание работает без него.",
    "The transcript as is, without cleanup.": "Расшифровка как есть, без очистки.",
    "The skill did not run, inserted the text without it": "Скилл не сработал, текст вставлен без него",
    "The skill could not be imported": "Не удалось импортировать скилл",
    "Your models, history, skills and API key are kept.": "Модели, история, скиллы и ключ API сохранятся.",
    "Start speaking after the sound": "Начинайте говорить после звука",
    "Numbers": "Числа",
    "As dictated": "Как продиктовано",
    "Digits: 25": "Цифрами: 25",
    "Words: twenty-five": "Словами: двадцать пять",
    "Currency symbols": "Значки валют",
    "“50 dollars” becomes “$50”, “50 euros” becomes “50 €”.": "«50 долларов» станет «$50», «50 евро» станет «50 €».",
    "Until %@ is downloaded, %@ recognizes your speech.": "Пока %1$@ загружается, речь распознаёт %2$@.",
    "%lld%% · %@ of %@": "%1$lld%% · %2$@ из %3$@",
    "andydev.space": "andydev.space",
    "© 2026 Andrei Bogdanov": "© 2026 Andrei Bogdanov",
    "Cancel": "Отменить",
    "%lld s": "%lld с",
    "OpenAI did not respond, recognized on this Mac": "OpenAI не ответил, распознано на этом Mac",
    "What is this?": "Что это?",
    "Paste (⌘V)": "Вставка (⌘V)",
    "Type letter by letter": "Набор по буквам",
    "Paste: Canto puts the text on the clipboard, presses ⌘V and then puts back what was on the clipboard before. Instant, works almost everywhere.\n\nType letter by letter: Canto types the text as if from the keyboard. Slower and may be affected by autocorrect, but the clipboard stays untouched. Useful where pasting is blocked.": "Вставка: Canto кладёт текст в буфер обмена, нажимает ⌘V и возвращает в буфер то, что там было. Мгновенно и работает почти везде.\n\nНабор по буквам: Canto печатает текст, как будто с клавиатуры. Медленнее, может мешать автозамена, зато буфер обмена не трогается. Пригодится там, где вставка запрещена.",
    "Both ways need Accessibility access. If Canto is already in that list but text is not inserted, remove it with “−” and allow it again.": "Обоим способам нужен Универсальный доступ. Если Canto уже есть в списке, а текст не вставляется, удалите его кнопкой «−» и разрешите снова.",
    "On this Mac: speech never leaves your Mac and works without the internet. Speed and accuracy depend on the downloaded model.\n\nOpenAI: needs the internet and an API key and is paid per minute. If OpenAI does not answer, Canto uses a downloaded model on this Mac instead.": "На этом Mac: речь никуда не отправляется, работает без интернета. Скорость и точность зависят от загруженной модели.\n\nOpenAI: нужны интернет и ключ API, оплата поминутная. Если OpenAI не отвечает, Canto распознаёт загруженной моделью на этом Mac.",
    "Fast takes the most likely word at each step. Balanced and Thorough compare several variants of the phrase: a little more accurate on unclear speech, but noticeably slower.": "«Быстро» берёт самое вероятное слово на каждом шаге. «Сбалансированно» и «Тщательно» сравнивают несколько вариантов фразы: чуть точнее на неразборчивой речи, но заметно медленнее.",
    "Vocabulary": "Словарь",
    "Add a word": "Добавить слово",
    "For example, Kubernetes": "Например, Kubernetes",
    "Add": "Добавить",
    "Names and terms to write exactly like this, such as OpenAI or ChatGPT, instead of spelling them out phonetically. They guide recognition and do not slow it down.": "Имена и термины, которые нужно писать именно так, например OpenAI или ChatGPT, а не русскими буквами. Они подсказывают распознаванию и не замедляют его.",
    "GPT-4o models usually recognize speech and terms more accurately than Whisper. For the fastest results without the internet, use Large v3 Turbo on this Mac.": "Модели GPT-4o обычно точнее Whisper распознают речь и термины. Быстрее всего и без интернета — Large v3 Turbo на этом Mac.",
    "Whisper: 99 languages, takes the vocabulary into account while recognizing": "Whisper: 99 языков, учитывает словарь при распознавании",
    "No longer offered. Delete it to free up space.": "Больше не поддерживается. Удалите, чтобы освободить место.",
    "Small and fast, less accurate": "Маленькая и быстрая, но менее точная",
    "What the model heard, before punctuation, numbers and the skill": "Что услышала модель, до пунктуации, чисел и скилла",
    "Recognized text, for example from History": "Распознанный текст, например из истории",
    "Try the processing": "Проверка обработки",
    "Run": "Проверить",
    "The skill did not run: %@": "Скилл не сработал: %@",
    "The text goes through the same steps as dictation with the current settings: punctuation, numbers, vocabulary and the skill. History shows what the model heard under each entry.": "Текст проходит те же шаги, что и диктовка, с текущими настройками: пунктуацию, числа, словарь и скилл. В истории под каждой записью видно, что услышала модель.",
    "Fastest, on the Neural Engine; 25 European languages": "Самая быстрая, на Neural Engine; 25 европейских языков",
    "Parakeet does not recognize this language. Choose Large v3 Turbo.": "Parakeet не распознаёт этот язык. Выберите Large v3 Turbo.",
    "עברית": "עברית",
    "Time from the end of the phrase to the inserted text": "Время от конца фразы до вставки текста",
    "GPT-4o mini Transcribe": "GPT-4o mini Transcribe",
    "GPT-4o Transcribe": "GPT-4o Transcribe",
    "Whisper": "Whisper",
    "Default": "По умолчанию",
    "Auto": "Авто",
    "Find in Keychain…": "Найти в Связке ключей…",
    "No OpenAI keys were found in the keychain": "В Связке ключей нет ключей OpenAI",
    "The keychain item could not be read": "Не удалось прочитать запись из Связки ключей",
    "“%@” does not look like an OpenAI key": "«%@» не похоже на ключ OpenAI",
    "Choose an OpenAI key": "Выберите ключ OpenAI",
    "macOS will ask to allow access to the selected item.": "macOS попросит разрешить доступ к выбранной записи.",
    "%@ (%@)": "%1$@ (%2$@)",
    "Your latest transcripts will appear here": "Здесь появятся последние расшифровки",
    "%lld more": "Ещё %lld",
    "%@ · %lld MB": "%1$@ · %2$lld МБ",
    "%lld": "%lld",
    "%lld %%": "%lld %%",
    "AI": "ИИ",
    "API key": "Ключ API",
    "About": "О программе",
    "Accessibility": "Универсальный доступ",
    "Add Key…": "Добавить ключ…",
    "Add your OpenAI API key": "Добавьте ключ API OpenAI",
    "Advanced": "Дополнительно",
    "Allow Accessibility to insert text": "Разрешите Универсальный доступ для вставки текста",
    "Allow microphone access": "Разрешите доступ к микрофону",
    "Allowed": "Разрешено",
    "Allow…": "Разрешить…",
    "Audio": "Звук",
    "Audio is sent to OpenAI for recognition. Add your API key in Text & AI.": "Звук отправляется в OpenAI для распознавания. Добавьте ключ API в разделе «Текст и ИИ».",
    "Audio kept before speech": "Звук до начала речи",
    "Back": "Назад",
    "Balanced": "Сбалансированно",
    "Basic cleanup": "Базовая очистка",
    "Built with whisper.cpp (MIT), FluidAudio (Apache 2.0), Silero VAD (MIT) and libfvad (BSD).": "Создано на основе whisper.cpp (MIT), FluidAudio (Apache 2.0), Silero VAD (MIT) и libfvad (BSD).",
    "Cancel download": "Отменить загрузку",
    "Caps Lock could not be remapped": "Не удалось переназначить Caps Lock",
    "Choose…": "Выбрать…",
    "Clean up audio before recognition": "Очищать звук перед распознаванием",
    "Cleanup": "Очистка",
    "Clear All…": "Очистить всё…",
    "Click and press a new shortcut": "Нажмите и введите новое сочетание клавиш",
    "Continue": "Продолжить",
    "Copied. Allow Accessibility to paste automatically": "Скопировано. Разрешите Универсальный доступ для автоматической вставки",
    "Copy": "Скопировать",
    "Data folder": "Папка данных",
    "Decoding": "Декодирование",
    "Delete": "Удалить",
    "Delete All": "Удалить все",
    "Delete all transcripts?": "Удалить все расшифровки?",
    "Detect automatically": "Определять автоматически",
    "Dictate anywhere on your Mac. Speech is recognized on device, cleaned up and typed into the app you are using.": "Диктуйте в любом приложении на Mac. Речь распознаётся на устройстве, очищается и вставляется туда, где вы работаете.",
    "Dictate into any app on your Mac. Hold a shortcut, speak, and the text appears where your cursor is.": "Диктуйте в любое приложение на Mac. Удерживайте сочетание клавиш, говорите — и текст появится там, где курсор.",
    "Dictation": "Диктовка",
    "Download": "Загрузить",
    "Download a speech model": "Загрузите модель распознавания",
    "Enable dictation": "Включить диктовку",
    "End a dictation with this phrase to insert the text and press Return, for example to send a chat message.": "Закончите диктовку этой фразой, чтобы вставить текст и нажать Return, например чтобы отправить сообщение в чате.",
    "Engine": "Движок",
    "English": "English",
    "Everything you dictate appears here.": "Здесь появится всё, что вы надиктуете.",
    "Fast": "Быстро",
    "Feedback": "Обратная связь",
    "Fix": "Исправить",
    "General": "Основные",
    "Get a Key": "Получить ключ",
    "History": "История",
    "History stays on this Mac. Up to 200 recent transcripts are kept.": "История хранится только на этом Mac. Сохраняются до 200 последних расшифровок.",
    "Hold": "Удержание",
    "Hold it while you speak and release to insert the text.": "Удерживайте её, пока говорите, и отпустите, чтобы вставить текст.",
    "Hold the shortcut while you speak, release to insert.": "Удерживайте сочетание клавиш, пока говорите, отпустите для вставки.",
    "Hold to dictate, release to insert": "Удерживайте для диктовки, отпустите для вставки",
    "Hold to talk": "Удерживать для диктовки",
    "If the selected microphone is disconnected, Canto uses the system default.": "Если выбранный микрофон отключён, Canto использует системный по умолчанию.",
    "Import…": "Импортировать…",
    "Input level": "Уровень входа",
    "Insert text by": "Способ вставки",
    "Inserted": "Вставлено",
    "Insertion": "Вставка",
    "Installed": "Установлена",
    "Interface": "Интерфейс",
    "Keep a history of transcripts": "Сохранять историю расшифровок",
    "Language": "Язык",
    "Listening": "Слушаю",
    "Longest phrase": "Самая длинная фраза",
    "Microphone": "Микрофон",
    "Mode": "Режим",
    "Model": "Модель",
    "Models": "Модели",
    "Models folder": "Папка моделей",
    "Much faster on Apple silicon.": "Намного быстрее на Apple silicon.",
    "Needs setup": "Нужна настройка",
    "No Transcripts Yet": "Расшифровок пока нет",
    "No connection to OpenAI": "Нет связи с OpenAI",
    "None": "Нет",
    "Off": "Выключено",
    "On Intel Macs the processor is usually faster.": "На Mac с Intel процессор обычно быстрее.",
    "On this Mac": "На этом Mac",
    "On this Mac (Whisper)": "На этом Mac (Whisper)",
    "Open Folder": "Открыть папку",
    "Open Canto at login": "Открывать Canto при входе",
    "OpenAI": "OpenAI",
    "OpenAI quota exceeded": "Превышена квота OpenAI",
    "OpenAI rejected the API key": "OpenAI отклонил ключ API",
    "Original": "Оригинал",
    "Pasting": "Вставкой",
    "Pasting is instant and restores your clipboard afterwards. Typing leaves the clipboard alone but is slower. Both need Accessibility access. If Canto is already in that list but text is not inserted, remove it with “−” and allow it again.": "Вставка мгновенна и потом возвращает содержимое буфера обмена. Набор не трогает буфер, но медленнее. Для обоих способов нужен Универсальный доступ. Если Canto уже есть в списке, а текст не вставляется, удалите его кнопкой «−» и разрешите снова.",
    "Pause that ends a phrase": "Пауза, завершающая фразу",
    "Performance": "Производительность",
    "Phrase": "Фраза",
    "Play sounds": "Воспроизводить звуки",
    "Press Return after a phrase": "Нажимать Return после фразы",
    "Press shortcut…": "Нажмите сочетание…",
    "Press the shortcut again to finish": "Нажмите сочетание ещё раз, чтобы закончить",
    "Press to start and stop": "Нажатие — старт и стоп",
    "Press to start dictation, press again to finish": "Нажмите, чтобы начать диктовку, и ещё раз, чтобы закончить",
    "Processing": "Обработка",
    "Quit": "Завершить",
    "Ready": "Готово",
    "Recent": "Недавние",
    "Recognition": "Распознавание",
    "Recognize speech privately on this Mac, or with OpenAI.": "Распознавайте речь приватно на этом Mac или через OpenAI.",
    "Release to insert": "Отпустите для вставки",
    "Remove": "Удалить",
    "Removes repeated words, fixes spacing and capitalization.": "Убирает повторы слов, исправляет пробелы и заглавные буквы.",
    "Removes low rumble, evens out loudness and skips silent recordings.": "Убирает низкочастотный гул, выравнивает громкость и пропускает тихие записи.",
    "Reset": "Сбросить",
    "Reset all settings?": "Сбросить все настройки?",
    "Reset to Defaults…": "Сбросить настройки…",
    "Restart Canto": "Перезапустить Canto",
    "Save": "Сохранить",
    "Saved in the keychain": "Сохранён в Связке ключей",
    "Saved transcripts": "Сохранённые расшифровки",
    "Say “comma”, “period” or “new paragraph” to insert them.": "Скажите «запятая», «точка» или «новый абзац», чтобы вставить их.",
    "Search": "Поиск",
    "Send": "Отправка",
    "Settings": "Настройки",
    "Setup": "Настройка",
    "Settings…": "Настройки…",
    "Shortcut": "Сочетание клавиш",
    "Shortest phrase": "Самая короткая фраза",
    "Show All": "Показать все",
    "Show History…": "Показать историю…",
    "Show Welcome Guide…": "Показать приветствие…",
    "Show in Finder": "Показать в Finder",
    "Show the recording overlay": "Показывать индикатор записи",
    "Something went wrong": "Что-то пошло не так",
    "Speak naturally: every pause inserts the phrase you just said.": "Говорите естественно: каждая пауза вставляет только что сказанную фразу.",
    "Speech detection": "Определение речи",
    "Speech is recognized on your Mac and never leaves it.": "Речь распознаётся на вашем Mac и никуда не отправляется.",
    "Speech recognition": "Распознавание речи",
    "Spoken language": "Язык речи",
    "Spoken punctuation": "Произносимая пунктуация",
    "Start Using Canto": "Начать работу",
    "Stop": "Стоп",
    "System": "Системный",
    "System default": "Системный по умолчанию",
    "System default (%@)": "Системный по умолчанию (%@)",
    "Test": "Проверить",
    "Text": "Текст",
    "Text & AI": "Текст и ИИ",
    "The key could not be saved to the keychain": "Не удалось сохранить ключ в Связку ключей",
    "The microphone changed, listening stopped": "Микрофон изменился, запись остановлена",
    "The microphone could not be started": "Не удалось включить микрофон",
    "The microphone did not respond. Try again or choose another one": "Микрофон не ответил. Попробуйте ещё раз или выберите другой",
    "The model download failed": "Не удалось загрузить модель",
    "The new language is used after a restart.": "Новый язык применится после перезапуска.",
    "The pause applies to Press to start and stop mode. Long phrases are split so each part is recognized quickly.": "Пауза действует в режиме «Нажатие — старт и стоп». Длинные фразы делятся на части, чтобы каждая распознавалась быстро.",
    "The speech model could not be loaded": "Не удалось загрузить модель распознавания",
    "This shortcut is used by another app": "Это сочетание занято другим приложением",
    "This shortcut is used by another app. Choose a different one.": "Это сочетание занято другим приложением. Выберите другое.",
    "Thorough": "Тщательно",
    "To insert the text into the app you are using.": "Чтобы вставлять текст в приложение, с которым вы работаете.",
    "To record while you dictate.": "Чтобы записывать звук во время диктовки.",
    "Toggle": "Переключение",
    "Transcribing": "Распознаю",
    "Transcribing…": "Распознаю…",
    "Transcription failed": "Не удалось распознать речь",
    "Try it here": "Попробуйте здесь",
    "Turn dictation on or off": "Включить или выключить диктовку",
    "Turning speech into text…": "Превращаю речь в текст…",
    "Two permissions": "Два разрешения",
    "Typing": "Набором",
    "Unavailable device": "Недоступное устройство",
    "Use Caps Lock as the dictation key": "Caps Lock — клавиша диктовки",
    "Use Default Folder": "Папка по умолчанию",
    "Use the GPU (Metal)": "Использовать GPU (Metal)",
    "Use this model": "Использовать эту модель",
    "Version %@": "Версия %@",
    "Canto": "Canto",
    "Canto needs to hear you and to type for you. You can change this later in System Settings.": "Canto нужно слышать вас и печатать за вас. Это можно изменить позже в Системных настройках.",
    "Welcome to Canto": "Добро пожаловать в Canto",
    "While Canto runs, Caps Lock acts as F18 and becomes the shortcut. Turn this off or quit Canto to get Caps Lock back.": "Пока Canto открыто, Caps Lock действует как F18 и становится сочетанием для диктовки. Выключите параметр или закройте Canto, чтобы вернуть Caps Lock.",
    "Write numbers as words": "Писать числа словами",
    "Your OpenAI API key is saved.": "Ключ API OpenAI сохранён.",
    "Your dictation key": "Клавиша диктовки",
    "for example “send it”": "например «отправить»",
    "sk-…": "sk-…",
    "whisper-1": "whisper-1",
    "whisper.cpp on GitHub": "whisper.cpp на GitHub",
    "·": "·",
    "Русский": "Русский",
    "“42” becomes “forty-two”.": "«42» станет «сорок два».",
}

DO_NOT_TRANSLATE = {"andydev.space", "© 2026 Andrei Bogdanov", "GPT-4o mini Transcribe", "GPT-4o Transcribe", "Whisper", "Large v3 Turbo", "Parakeet v3", "%@ (%@)", "%lld", "%lld %%", "English", "OpenAI", "Canto", "sk-…", "whisper-1", "·", "Русский", "עברית"}

def unit(value):
    return {"stringUnit": {"state": "translated", "value": value}}

def catalog(entries, hebrew):
    strings = {}
    for key, value in sorted(entries.items()):
        if key in DO_NOT_TRANSLATE:
            strings[key] = {"shouldTranslate": False}
        else:
            strings[key] = {"localizations": {"he": unit(hebrew[key]), "ru": unit(value)}}
    return {"sourceLanguage": "en", "strings": strings, "version": "1.0"}

def write(name, entries, hebrew):
    missing = [key for key in entries if key not in DO_NOT_TRANSLATE and key not in hebrew]
    if missing:
        raise SystemExit(f"{name}: no Hebrew for {missing}")
    path = os.path.join(ROOT, "Canto", "Resources", name)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(catalog(entries, hebrew), f, ensure_ascii=False, indent=2, separators=(",", " : "))
        f.write("\n")
    print(f"{name}: {len(entries)} strings")

if __name__ == "__main__":
    write("Localizable.xcstrings", RU, HE)
    write("InfoPlist.xcstrings", {
        "CFBundleDisplayName": "Canto",
        "NSMicrophoneUsageDescription": "Canto записывает звук с микрофона, чтобы превратить вашу речь в текст.",
    }, INFO_PLIST_HE)
