"""Hebrew interface strings for make-strings.py. Buttons and labels are nouns or infinitives and
instructions are impersonal, so the text does not assume the reader's gender."""

HE = {
    "Starting the microphone…": "הפעלת המיקרופון…",
    "Unload the model after": "פריקת המודל מהזיכרון אחרי",
    "Never": "אף פעם",
    "1 minute": "דקה אחת",
    "5 minutes": "5 דקות",
    "15 minutes": "15 דקות",
    "Frees memory while you are not dictating. The model loads again when you press the shortcut, usually while you are still speaking.": "משחרר זיכרון כשאין הכתבה. המודל נטען מחדש בלחיצה על קיצור המקשים, בדרך כלל עוד בזמן הדיבור.",
    "AI skills": "מיומנויות AI",
    "Skills": "מיומנויות",
    "Turn off all skills": "כיבוי כל המיומנויות",
    "Runs on": "פועל דרך",
    "Local server": "שרת מקומי",
    "Server": "שרת",
    "Reload skills": "רענון המיומנויות",
    "Ollama: http://localhost:11434/v1, LM Studio: http://localhost:1234/v1. The text stays on your Mac.": "Ollama: http://localhost:11434/v1, LM Studio: http://localhost:1234/v1. הטקסט נשאר ב-Mac שלך.",
    "A skill is a Markdown file with instructions for the AI: clean up, organize, fix technical terms, translate. Skills that are on run together in one request after the cleanup and add about a second; the number shows their order.": "מיומנות היא קובץ Markdown עם הוראות ל-AI: לנקות, לארגן, לתקן מונחים טכניים, לתרגם. המיומנויות המופעלות רצות יחד בבקשה אחת אחרי הניקוי ומוסיפות כשנייה; המספר מציין את הסדר שלהן.",
    "Needed for skills on OpenAI and for recognition with OpenAI. Local recognition works without it.": "נדרש למיומנויות ולזיהוי דרך OpenAI. זיהוי מקומי עובד בלעדיו.",
    "The transcript as is, without cleanup.": "התמלול כפי שהוא, ללא ניקוי.",
    "The skill did not run, inserted the text without it": "המיומנות לא רצה, הטקסט הוכנס בלעדיה",
    "The skill could not be imported": "לא ניתן לייבא את המיומנות",
    "Your models, history, skills and API key are kept.": "המודלים, ההיסטוריה, המיומנויות ומפתח ה-API יישמרו.",
    "Start speaking after the sound": "אפשר להתחיל לדבר אחרי הצליל",
    "Numbers": "מספרים",
    "As dictated": "כפי שהוכתב",
    "Digits: 25": "ספרות: 25",
    "Words: twenty-five": "מילים: עשרים וחמש",
    "Currency symbols": "סמלי מטבע",
    "“50 dollars” becomes “$50”, “50 euros” becomes “50 €”.": "\"50 דולר\" יהפוך ל-\"$50\", \"50 יורו\" ל-\"50 €\".",
    "Until %@ is downloaded, %@ recognizes your speech.": "עד שההורדה של %1$@ תסתיים, %2$@ מזהה את הדיבור.",
    "%lld%% · %@ of %@": "%1$lld%% · %2$@ מתוך %3$@",
    "Cancel": "ביטול",
    "%lld s": "%lld שנ׳",
    "OpenAI did not respond, recognized on this Mac": "OpenAI לא הגיב, הזיהוי בוצע ב-Mac הזה",
    "What is this?": "מה זה?",
    "Paste (⌘V)": "הדבקה (⌘V)",
    "Type letter by letter": "הקלדה אות אחר אות",
    "Paste: Canto puts the text on the clipboard, presses ⌘V and then puts back what was on the clipboard before. Instant, works almost everywhere.\n\nType letter by letter: Canto types the text as if from the keyboard. Slower and may be affected by autocorrect, but the clipboard stays untouched. Useful where pasting is blocked.": "הדבקה: Canto מעתיק את הטקסט ללוח, לוחץ ⌘V ומחזיר ללוח את מה שהיה בו קודם. מיידי ועובד כמעט בכל מקום.\n\nהקלדה אות אחר אות: Canto מקליד את הטקסט כאילו מהמקלדת. איטי יותר ותיקון אוטומטי עלול להפריע, אבל הלוח לא משתנה. שימושי במקומות שבהם הדבקה חסומה.",
    "Both ways need Accessibility access. If Canto is already in that list but text is not inserted, remove it with “−” and allow it again.": "שתי השיטות דורשות הרשאת נגישות. אם Canto כבר ברשימה אבל הטקסט לא מוכנס, יש להסיר אותו בכפתור \"−\" ולאשר שוב.",
    "On this Mac: speech never leaves your Mac and works without the internet. Speed and accuracy depend on the downloaded model.\n\nOpenAI: needs the internet and an API key and is paid per minute. If OpenAI does not answer, Canto uses a downloaded model on this Mac instead.": "ב-Mac הזה: הדיבור לא יוצא מה-Mac ועובד בלי אינטרנט. המהירות והדיוק תלויים במודל שהורד.\n\nOpenAI: דורש אינטרנט ומפתח API, והתשלום הוא לפי דקה. אם OpenAI לא עונה, Canto משתמש במקום זאת במודל שהורד ל-Mac הזה.",
    "Fast takes the most likely word at each step. Balanced and Thorough compare several variants of the phrase: a little more accurate on unclear speech, but noticeably slower.": "\"מהיר\" בוחר בכל שלב את המילה הסבירה ביותר. \"מאוזן\" ו\"יסודי\" משווים כמה גרסאות של המשפט: מעט מדויקים יותר בדיבור לא ברור, אבל איטיים יותר באופן מורגש.",
    "Vocabulary": "מילון",
    "Add a word": "הוספת מילה",
    "For example, Kubernetes": "לדוגמה, Kubernetes",
    "Add": "הוספה",
    "Names and terms to write exactly like this, such as OpenAI or ChatGPT, instead of spelling them out phonetically. They guide recognition and do not slow it down.": "שמות ומונחים שייכתבו בדיוק כך, למשל OpenAI או ChatGPT, במקום בתעתיק לפי הצליל. הם מכוונים את הזיהוי ולא מאטים אותו.",
    "GPT-4o models usually recognize speech and terms more accurately than Whisper. For the fastest results without the internet, use Large v3 Turbo on this Mac.": "מודלי GPT-4o מזהים בדרך כלל דיבור ומונחים בדיוק רב יותר מ-Whisper. לתוצאות המהירות ביותר בלי אינטרנט: Large v3 Turbo ב-Mac הזה.",
    "Whisper: 99 languages, takes the vocabulary into account while recognizing": "Whisper: 99 שפות, מתחשב במילון בזמן הזיהוי",
    "No longer offered. Delete it to free up space.": "כבר לא נתמך. אפשר למחוק כדי לפנות מקום.",
    "Small and fast, less accurate": "קטן ומהיר, פחות מדויק",
    "What the model heard, before punctuation, numbers and the skill": "מה שהמודל שמע, לפני פיסוק, מספרים ומיומנות",
    "Recognized text, for example from History": "טקסט מזוהה, למשל מההיסטוריה",
    "Try the processing": "בדיקת העיבוד",
    "Run": "הרצה",
    "The skill did not run: %@": "המיומנות לא רצה: %@",
    "The text goes through the same steps as dictation with the current settings: punctuation, numbers, vocabulary and the skill. History shows what the model heard under each entry.": "הטקסט עובר את אותם שלבים כמו בהכתבה, עם ההגדרות הנוכחיות: פיסוק, מספרים, מילון ומיומנות. בהיסטוריה מופיע מתחת לכל רשומה מה שהמודל שמע.",
    "Fastest, on the Neural Engine; 25 European languages": "המהיר ביותר, על Neural Engine; 25 שפות אירופיות",
    "Parakeet does not recognize this language. Choose Large v3 Turbo.": "Parakeet לא מזהה את השפה הזו. יש לבחור ב-Large v3 Turbo.",
    "Time from the end of the phrase to the inserted text": "הזמן מסוף המשפט ועד הכנסת הטקסט",
    "Default": "ברירת מחדל",
    "Auto": "אוטומטי",
    "Find in Keychain…": "חיפוש במחזיק המפתחות…",
    "No OpenAI keys were found in the keychain": "לא נמצאו מפתחות OpenAI במחזיק המפתחות",
    "The keychain item could not be read": "לא ניתן לקרוא את הפריט ממחזיק המפתחות",
    "“%@” does not look like an OpenAI key": "\"%@\" לא נראה כמו מפתח OpenAI",
    "Choose an OpenAI key": "בחירת מפתח OpenAI",
    "macOS will ask to allow access to the selected item.": "macOS יבקש לאשר גישה לפריט שנבחר.",
    "Your latest transcripts will appear here": "התמלולים האחרונים יופיעו כאן",
    "%lld more": "עוד %lld",
    "%@ · %lld MB": "%1$@ · %2$lld MB",
    "AI": "AI",
    "API key": "מפתח API",
    "About": "אודות",
    "Accessibility": "נגישות",
    "Add Key…": "הוספת מפתח…",
    "Add your OpenAI API key": "יש להוסיף מפתח API של OpenAI",
    "Advanced": "מתקדם",
    "Allow Accessibility to insert text": "יש לאשר נגישות כדי להכניס טקסט",
    "Allow microphone access": "יש לאשר גישה למיקרופון",
    "Allowed": "מאושר",
    "Allow…": "אישור…",
    "Audio": "שמע",
    "Audio is sent to OpenAI for recognition. Add your API key in Text & AI.": "השמע נשלח ל-OpenAI לזיהוי. יש להוסיף מפתח API בחלק \"טקסט ו-AI\".",
    "Audio kept before speech": "שמע שנשמר לפני הדיבור",
    "Back": "חזרה",
    "Balanced": "מאוזן",
    "Basic cleanup": "ניקוי בסיסי",
    "Built with whisper.cpp (MIT), FluidAudio (Apache 2.0) and libfvad (BSD).": "נבנה עם whisper.cpp (MIT), FluidAudio (Apache 2.0) ו-libfvad (BSD).",
    "Cancel download": "ביטול ההורדה",
    "Caps Lock could not be remapped": "לא ניתן למפות מחדש את Caps Lock",
    "Choose…": "בחירה…",
    "Clean up audio before recognition": "ניקוי השמע לפני הזיהוי",
    "Cleanup": "ניקוי",
    "Clear All…": "ניקוי הכול…",
    "Click and press a new shortcut": "יש ללחוץ כאן ולהקיש קיצור מקשים חדש",
    "Continue": "המשך",
    "Copied. Allow Accessibility to paste automatically": "הועתק. יש לאשר נגישות כדי להדביק אוטומטית",
    "Copy": "העתקה",
    "Data folder": "תיקיית נתונים",
    "Decoding": "פענוח",
    "Delete": "מחיקה",
    "Delete All": "מחיקת הכול",
    "Delete all transcripts?": "למחוק את כל התמלולים?",
    "Detect automatically": "זיהוי אוטומטי",
    "Dictate anywhere on your Mac. Speech is recognized on device, cleaned up and typed into the app you are using.": "הכתבה בכל מקום ב-Mac. הדיבור מזוהה במכשיר, מנוקה ומוקלד ביישום שבו עובדים.",
    "Dictate into any app on your Mac. Hold a shortcut, speak, and the text appears where your cursor is.": "הכתבה לכל יישום ב-Mac. מחזיקים קיצור מקשים, מדברים, והטקסט מופיע במקום הסמן.",
    "Dictation": "הכתבה",
    "Download": "הורדה",
    "Download a speech model": "יש להוריד מודל זיהוי דיבור",
    "Enable dictation": "הפעלת הכתבה",
    "End a dictation with this phrase to insert the text and press Return, for example to send a chat message.": "אפשר לסיים הכתבה בביטוי הזה כדי להכניס את הטקסט וללחוץ Return, למשל כדי לשלוח הודעה בצ׳אט.",
    "Engine": "מנוע",
    "Everything you dictate appears here.": "כל מה שמכתיבים יופיע כאן.",
    "Fast": "מהיר",
    "Feedback": "משוב",
    "Fix": "תיקון",
    "General": "כללי",
    "Get a Key": "קבלת מפתח",
    "History": "היסטוריה",
    "History stays on this Mac. Up to 200 recent transcripts are kept.": "ההיסטוריה נשמרת רק ב-Mac הזה. נשמרים עד 200 התמלולים האחרונים.",
    "Hold": "החזקה",
    "Hold it while you speak and release to insert the text.": "מחזיקים אותו בזמן הדיבור ומשחררים כדי להכניס את הטקסט.",
    "Hold the shortcut while you speak, release to insert.": "מחזיקים את קיצור המקשים בזמן הדיבור ומשחררים להכנסה.",
    "Hold to dictate, release to insert": "להחזיק להכתבה, לשחרר להכנסה",
    "Hold to talk": "החזקה לדיבור",
    "If the selected microphone is disconnected, Canto uses the system default.": "אם המיקרופון שנבחר מנותק, Canto משתמש בברירת המחדל של המערכת.",
    "Import…": "ייבוא…",
    "Input level": "עוצמת קלט",
    "Insert text by": "אופן הכנסת הטקסט",
    "Inserted": "הוכנס",
    "Insertion": "הכנסה",
    "Installed": "מותקן",
    "Interface": "ממשק",
    "Keep a history of transcripts": "שמירת היסטוריית תמלולים",
    "Language": "שפה",
    "Listening": "האזנה",
    "Longest phrase": "המשפט הארוך ביותר",
    "Microphone": "מיקרופון",
    "Mode": "מצב",
    "Model": "מודל",
    "Models": "מודלים",
    "Models folder": "תיקיית מודלים",
    "Much faster on Apple silicon.": "מהיר בהרבה על Apple silicon.",
    "Needs setup": "נדרשת הגדרה",
    "No Transcripts Yet": "אין עדיין תמלולים",
    "No connection to OpenAI": "אין חיבור ל-OpenAI",
    "None": "ללא",
    "Off": "כבוי",
    "On Intel Macs the processor is usually faster.": "במחשבי Mac עם Intel המעבד בדרך כלל מהיר יותר.",
    "On this Mac": "ב-Mac הזה",
    "On this Mac (Whisper)": "ב-Mac הזה (Whisper)",
    "Open Folder": "פתיחת התיקייה",
    "Open Canto at login": "פתיחת Canto בהתחברות",
    "OpenAI quota exceeded": "המכסה של OpenAI נוצלה",
    "OpenAI rejected the API key": "OpenAI דחה את מפתח ה-API",
    "Original": "מקורי",
    "Pasting": "הדבקה",
    "Pasting is instant and restores your clipboard afterwards. Typing leaves the clipboard alone but is slower. Both need Accessibility access. If Canto is already in that list but text is not inserted, remove it with “−” and allow it again.": "הדבקה היא מיידית ומחזירה אחר כך את תוכן הלוח. הקלדה לא נוגעת בלוח אבל איטית יותר. שתי השיטות דורשות הרשאת נגישות. אם Canto כבר ברשימה אבל הטקסט לא מוכנס, יש להסיר אותו בכפתור \"−\" ולאשר שוב.",
    "Pause that ends a phrase": "הפסקה שמסיימת משפט",
    "Performance": "ביצועים",
    "Phrase": "משפט",
    "Play sounds": "השמעת צלילים",
    "Press Return after a phrase": "לחיצה על Return אחרי משפט",
    "Press shortcut…": "יש להקיש קיצור…",
    "Press the shortcut again to finish": "לחיצה נוספת על הקיצור מסיימת",
    "Press to start and stop": "לחיצה להתחלה ולעצירה",
    "Press to start dictation, press again to finish": "לחיצה מתחילה הכתבה, לחיצה נוספת מסיימת",
    "Processing": "עיבוד",
    "Quit": "יציאה",
    "Ready": "מוכן",
    "Recent": "אחרונים",
    "Recognition": "זיהוי",
    "Recognize speech privately on this Mac, or with OpenAI.": "זיהוי דיבור באופן פרטי ב-Mac הזה, או דרך OpenAI.",
    "Release to insert": "לשחרר להכנסה",
    "Remove": "הסרה",
    "Removes repeated words, fixes spacing and capitalization.": "מסיר מילים חוזרות, מתקן רווחים ואותיות רישיות.",
    "Removes low rumble, evens out loudness and skips silent recordings.": "מסיר רעש נמוך, מאזן עוצמה ומדלג על הקלטות שקטות.",
    "Reset": "איפוס",
    "Reset all settings?": "לאפס את כל ההגדרות?",
    "Reset to Defaults…": "איפוס לברירת המחדל…",
    "Restart Canto": "הפעלה מחדש של Canto",
    "Save": "שמירה",
    "Saved in the keychain": "נשמר במחזיק המפתחות",
    "Saved transcripts": "תמלולים שמורים",
    "Say “comma”, “period” or “new paragraph” to insert them.": "אפשר לומר \"פסיק\", \"נקודה\" או \"פסקה חדשה\" כדי להכניס אותם.",
    "Search": "חיפוש",
    "Send": "שליחה",
    "Settings": "הגדרות",
    "Setup": "הגדרה",
    "Settings…": "הגדרות…",
    "Shortcut": "קיצור מקשים",
    "Shortest phrase": "המשפט הקצר ביותר",
    "Show All": "הצגת הכול",
    "Show History…": "הצגת ההיסטוריה…",
    "Show Welcome Guide…": "הצגת מדריך הפתיחה…",
    "Show in Finder": "הצגה ב-Finder",
    "Show the recording overlay": "הצגת מחוון ההקלטה",
    "Something went wrong": "משהו השתבש",
    "Speak naturally: every pause inserts the phrase you just said.": "מדברים באופן טבעי: כל הפסקה מכניסה את המשפט שנאמר זה עתה.",
    "Speech detection": "גילוי דיבור",
    "Speech is recognized on your Mac and never leaves it.": "הדיבור מזוהה ב-Mac ולא יוצא ממנו.",
    "Speech recognition": "זיהוי דיבור",
    "Spoken language": "שפת הדיבור",
    "Spoken punctuation": "פיסוק קולי",
    "Start Using Canto": "התחלת העבודה",
    "Stop": "עצירה",
    "System": "לפי המערכת",
    "System default": "ברירת המחדל של המערכת",
    "System default (%@)": "ברירת המחדל של המערכת (%@)",
    "Test": "בדיקה",
    "Text": "טקסט",
    "Text & AI": "טקסט ו-AI",
    "The key could not be saved to the keychain": "לא ניתן לשמור את המפתח במחזיק המפתחות",
    "The microphone changed, listening stopped": "המיקרופון השתנה, ההאזנה נעצרה",
    "The microphone could not be started": "לא ניתן להפעיל את המיקרופון",
    "The microphone did not respond. Try again or choose another one": "המיקרופון לא הגיב. אפשר לנסות שוב או לבחור מיקרופון אחר",
    "The model download failed": "הורדת המודל נכשלה",
    "The new language is used after a restart.": "השפה החדשה תופעל אחרי הפעלה מחדש.",
    "The pause applies to Press to start and stop mode. Long phrases are split so each part is recognized quickly.": "ההפסקה חלה במצב \"לחיצה להתחלה ולעצירה\". משפטים ארוכים מחולקים כדי שכל חלק יזוהה מהר.",
    "The speech model could not be loaded": "לא ניתן לטעון את מודל הזיהוי",
    "This shortcut is used by another app": "הקיצור הזה בשימוש של יישום אחר",
    "This shortcut is used by another app. Choose a different one.": "הקיצור הזה בשימוש של יישום אחר. יש לבחור קיצור אחר.",
    "Thorough": "יסודי",
    "To insert the text into the app you are using.": "כדי להכניס את הטקסט ליישום שבו עובדים.",
    "To record while you dictate.": "כדי להקליט בזמן ההכתבה.",
    "Toggle": "הפעלה וכיבוי",
    "Transcribing": "תמלול",
    "Transcribing…": "תמלול…",
    "Transcription failed": "התמלול נכשל",
    "Try it here": "אפשר לנסות כאן",
    "Turn dictation on or off": "הפעלה או כיבוי של ההכתבה",
    "Turning speech into text…": "המרת דיבור לטקסט…",
    "Two permissions": "שתי הרשאות",
    "Typing": "הקלדה",
    "Unavailable device": "התקן לא זמין",
    "Use Caps Lock as the dictation key": "Caps Lock כמקש ההכתבה",
    "Use Default Folder": "שימוש בתיקיית ברירת המחדל",
    "Use the GPU (Metal)": "שימוש ב-GPU (Metal)",
    "Use this model": "שימוש במודל הזה",
    "Version %@": "גרסה %@",
    "Canto needs to hear you and to type for you. You can change this later in System Settings.": "Canto צריך לשמוע אותך ולהקליד בשבילך. אפשר לשנות זאת אחר כך בהגדרות המערכת.",
    "Welcome to Canto": "ברוכים הבאים ל-Canto",
    "While Canto runs, Caps Lock acts as F18 and becomes the shortcut. Turn this off or quit Canto to get Caps Lock back.": "כל עוד Canto פועל, Caps Lock מתפקד כ-F18 והופך לקיצור ההכתבה. כדי לקבל את Caps Lock בחזרה, יש לכבות את האפשרות או לצאת מ-Canto.",
    "Write numbers as words": "כתיבת מספרים במילים",
    "Your OpenAI API key is saved.": "מפתח ה-API של OpenAI נשמר.",
    "Your dictation key": "מקש ההכתבה",
    "for example “send it”": "למשל \"לשלוח\"",
    "whisper.cpp on GitHub": "whisper.cpp ב-GitHub",
    "“42” becomes “forty-two”.": "\"42\" יהפוך ל\"ארבעים ושתיים\".",
}

INFO_PLIST_HE = {
    "CFBundleDisplayName": "Canto",
    "NSMicrophoneUsageDescription": "Canto מקליט שמע מהמיקרופון כדי להפוך את הדיבור שלך לטקסט.",
}
